modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fatchicken"
version="1.0"
displayName="FatChicken"
authors="nameless"
description='''
肥鸡Mod
'''
[[dependencies.fatchicken]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.fatchicken]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"